#!/bin/sh
#/etc/init.d/button-watchdog

### BEGIN INIT INFO
# Provides:          button-watchdog
# Required-Start:    $network $local_fs $remote_fs mongodb
# Required-Stop:     $network $local_fs $remote_fs mongodb
# Should-Start:      $named
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: store button push events in local MongoDB.
# Description:       Capture button push events and feedback by LED blink.
#                    Events are stored in local MongoDB.
### END INIT INFO

export NVM_DIR="/home/pi/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

export NODE_PATH=$NODE_PATH:/home/pi/.nvm/versions/node/v6.11.2/bin/node
DAEMON=/home/pi/.nvm/versions/node/v6.11.2/bin/forever
APP_DIR=/home/pi/dev/button-watchdog/device

case "$1" in
start)
exec $DAEMON start --sourceDir=$APP_DIR index.js
;;
stop)
exec $DAEMON stop  --sourceDir=$APP_DIR index.js
;;
*)
echo "Usage: /etc/init.d/button-watchdog {start|stop}"
exit 1
;;
esac
exit 0
